name: Main

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  Tests_pandas:
    name: Tests pandas / files
    runs-on: ${{ matrix.os }}
    env:
      BACKENDS: "pandas csv parquet hdf5"
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python_version: ["3.7", "3.9"]
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: set up environment
      run: ./ci/setup_env.sh "${{ matrix.python_version }}" "$BACKENDS"
      shell: bash